django/PathEditor/PathEditor/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views as authtoken_views
from rest_framework.authtoken.views import obtain_auth_token
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
   openapi.Info(
      title="Trasy API",
      default_version='v1',
      description="API do zarządzania trasami i punktami użytkowników",
      contact=openapi.Contact(email="kontakt@example.com"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("Paths/", include("Paths.urls")),

    path('api/', include('Paths.api_urls')),
    path('sse/', include('Paths.sse_urls')),
    path('api/auth-token/', authtoken_views.obtain_auth_token, name='api_auth_token'),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path("admin/", admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/PathEditor/Paths/urls.py
from django.urls import path

from . import views
from . import sse_views

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('select-background/', views.select_background, name='select_background'),
    path('backgrounds/', views.background_show, name="background_show"),
    
    path('home/', views.home, name='home'),

    path('paths/', views.path_list, name='path_list'),
    path('paths/new/', views.path_create, name='path_create'),
    path('paths/<int:path_id>/', views.path_detail, name='path_detail'),
    path('paths/<int:path_id>/add_point/', views.point_add, name='point_add'),
    path('points/<int:point_id>/delete/', views.point_delete, name='point_delete'),
    path('paths/<int:path_id>/delete/', views.delete_path, name='delete_path'),
    path('register/', views.register, name='register'),

    path('boards/', views.board_list, name='board_list'),
    path('boards/new/', views.board_create, name='board_create'),
    path('boards/<int:board_id>/', views.board_detail, name='board_detail'),

    path('allboards/', views.all_boards, name='allboard_list'),
    path('board_draw/<int:board_id>', views.board_draw, name='board_draw'),
]

django/PathEditor/Paths/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
from django.dispatch import receiver

class Background(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="backgrounds")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['title']

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    selected_background = models.ForeignKey(
        Background,
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        return self.user.username

class GameBoard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    rows = models.PositiveIntegerField()
    cols = models.PositiveIntegerField()
    
class Dot(models.Model):
    board = models.ForeignKey(GameBoard, on_delete=models.CASCADE, related_name='dots')
    row = models.PositiveIntegerField()
    col = models.PositiveIntegerField()
    color = models.CharField(max_length=7) 

class DotsJSON(models.Model):
    dots = models.JSONField()
    
class BoardPoint(models.Model):
    board = models.ForeignKey(GameBoard, on_delete=models.CASCADE, related_name='board_points')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_board_points')
    row = models.PositiveIntegerField()
    col = models.PositiveIntegerField()
    order = models.PositiveBigIntegerField()


def get_default_superuser():
    return User.objects.filter(is_superuser=True).first().id

class Path(models.Model):
    user = models.ForeignKey(
        to=User, on_delete=models.CASCADE,
        default=get_default_superuser,
        related_name="paths"
    )
    title = models.CharField(max_length=100)
    background = models.ForeignKey(to=Background, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        
        

class Point(models.Model):
    x = models.IntegerField()
    y = models.IntegerField()
    order = models.PositiveIntegerField()
    path = models.ForeignKey(to=Path, on_delete=models.CASCADE, related_name="points")

    def __str__(self):
        return f"Point ({self.x}, {self.y}) number: {self.order} of {self.path.title}"

    class Meta:
        unique_together = ['order', 'path']


class UserSelection(models.Model):
    selected_image = models.ForeignKey(Background, on_delete=models.CASCADE, null=True)

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def save_user_profile(sender, instance, **kwargs):
    if hasattr(instance, 'profile'):
        instance.profile.save()
    else:
        UserProfile.objects.create(user=instance)

django/PathEditor/Paths/forms.py
from django import forms
from .models import Path, Point, Background, UserSelection, GameBoard, DotsJSON, BoardPoint

class PathForm(forms.ModelForm):
    class Meta:
        model = Path
        fields = ['title']
        widgets = {
            'description': forms.Textarea(attrs={'rows':2}),
        }
        labels = {
            'title': 'Path title'
        }

class PathPointForm(forms.ModelForm):
    class Meta:
        model = Point
        fields = ['x', 'y']
        labels = {
            'x': 'X coordinate',
            'y': 'Y coordinate',
        }
        widgets = {
            'x': forms.NumberInput(attrs={'style': 'width: 80px;', 'min': '0'}),
            'y': forms.NumberInput(attrs={'style': 'width: 80px;', 'min': '0'}),
        }

class BoardForm(forms.ModelForm):
    class Meta:
        model = GameBoard
        fields = ['name', 'rows', 'cols']
        labels = {
            'name': 'Board name',
            'rows': 'Number of rows',
            'cols': 'Number of columns',
        }
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Board name'}),
            'rows': forms.NumberInput(attrs={'min': 1, 'style': 'width: 80px;'}),
            'cols': forms.NumberInput(attrs={'min': 1, 'style': 'width: 80px;'}),
        }

class BoardPointsForm(forms.Form):
    points = forms.JSONField(label="JSON of points")

class BoardPointForm(forms.ModelForm):
    class Meta:
        model = BoardPoint
        fields = ['row', 'col']
        labels = {
            'row': 'Row number',
            'col': 'Column number',
        }
        widgets = {
            'row': forms.NumberInput(attrs={'style': 'width: 80px;', 'min': '0'}),
            'col': forms.NumberInput(attrs={'style': 'width: 80px;', 'min': '0'}),
        }

django/PathEditor/Paths/views.py
from django.shortcuts import HttpResponse
from django.template import loader
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Max

from .forms import PathForm, PathPointForm, BoardForm, GameBoard, BoardPointsForm, BoardPointForm
from .models import Background, Path, Point, Dot
from .serializers import BoardPointsListSerializer

def home(request):
    if request.user.is_authenticated:
        return render(request, 'Paths/main.html', {
            'user': request.user
        })
    return render(request, 'Paths/home.html')

def background_show(request):
    background_list = Background.objects.all()
    template = loader.get_template("Paths/index.html")
    context = {"bg_list": background_list}
    return render(request, "Paths/index.html", context)

@login_required
def select_background(request):
    bgs = Background.objects.all()
    user_profile = request.user.profile

    if request.method == 'POST':
        background_id = request.POST.get('background_id')
        if not background_id:
            user_profile.selected_background = None
            user_profile.save()
            return redirect('path_list')
        
        selected_bg = Background.objects.get(id=background_id)
        user_profile.selected_background = selected_bg
        user_profile.save()
        return redirect('path_list')



    return render(request, 'Paths/bg_select.html', {
        'backgrounds': bgs,
        'current_background': user_profile.selected_background
    })

@login_required
def path_list(request):
    user = request.user
    profile = user.profile
    selected_background = profile.selected_background

    paths = Path.objects.filter(user=user, background=selected_background)

    if request.method == 'POST':
        if not selected_background:
            return redirect('select_background')

        path_form = PathForm(request.POST)
        if path_form.is_valid():
            new_path = path_form.save(commit=False)
            new_path.user = user
            new_path.background = selected_background
            new_path.save()
            return redirect('path_detail', path_id=new_path.id)
    else:
        path_form = PathForm()

    context = {
        'paths': paths,
        'selected_background': selected_background,
        'path_form': path_form,
    }
    return render(request, 'Paths/path_list.html', context)

@login_required
def path_create(request):
    if request.method == 'POST':
        form = PathForm(request.POST)
        if form.is_valid():
            path = form.save(commit=False)
            path.user = request.user
            path.background = request.user.profile.selected_background
            path.save()
            return redirect('path_detail', path_id=path.id)
    else:
        form = PathForm()
    return render(request, 'Paths/path_form.html', {'form': form})

@login_required
def path_detail(request, path_id):
    path = get_object_or_404(Path, id=path_id, user=request.user)
    points = path.points.order_by('order')
    point_form = PathPointForm(request.POST)
    if request.method == 'POST':
        if point_form.is_valid():
            last_point_order = points.aggregate(Max('order'))['order__max']
            next_order = (last_point_order or 0) + 1

            new_point = point_form.save(commit=False)
            new_point.path = path
            new_point.order = next_order
            new_point.save()
            return redirect('path_detail', path_id=path.id)

    return render(request, 'Paths/path_detail.html', {
        'path': path,
        'points': points,
        'point_form': point_form,
        'background': path.background
    })

@login_required
def point_add(request, path_id):
    path = get_object_or_404(path, id=path_id, user=request.user)
    if request.method == 'POST':
        form = PathPointForm(request.POST)
        if form.is_valid():
            point = form.save(commit=False)
            point.path = path
            point.save()
    return redirect('path_detail', path_id=path.id)

@login_required
def point_delete(request, point_id):
    point = get_object_or_404(Point, id=point_id)
    if point.path.user != request.user:
        return redirect('path_list')
    path_id = point.path.id
    point.delete()
    return redirect('path_detail', path_id=path_id)

@login_required
def delete_path(request, path_id):
    path = get_object_or_404(Path, id=path_id, user=request.user)
    path_name = path.title
    if request.method == 'POST':
        path.delete()
        return redirect('path_list')
    return redirect('path_list')


@login_required
def board_create(request): 
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.user = request.user
            board.name = form.cleaned_data['name']
            board.rows = form.cleaned_data['rows']
            board.cols = form.cleaned_data['cols']
            board.save()
            return redirect('board_detail', board_id=board.id)
    else:
        form = BoardForm()
    return render(request, 'Paths/board_form.html', {'form': form})

@login_required
def board_detail(request, board_id):
    board = get_object_or_404(GameBoard, id=board_id, user=request.user)
    dots = board.dots.all()

    if request.method == 'POST':
        board_form = BoardPointsForm(request.POST)
        if board_form.is_valid():
            points_data = board_form.cleaned_data['points']
            board.dots.all().delete()

            
            points = points_data
            for point in points:
                dot = Dot()
                dot.row = point['row']
                dot.col = point['col']
                dot.color = point['color']
                dot.board = board
                dot.save()
            return redirect('board_detail', board_id=board_id)
    board_form = BoardForm()

    return render(request, 'Paths/board_detail.html', {
        'board': board,
        'dots': dots,
        'cols': board.cols,
        'rows': board.rows,
        'board_form': board_form,
    })


@login_required
def board_list(request):
    user = request.user
    boards = GameBoard.objects.filter(user=user)

    context = {
        'boards': boards,
    }
    return render(request, 'Paths/board_list.html', context)
    
@login_required
def all_boards(request):
    boards=GameBoard.objects.all()
    return render(request, 'Paths/all_boards.html', {
        'boards': boards
    })

@login_required
def board_draw(request, board_id):
    board = get_object_or_404(GameBoard, id=board_id)
    board_points = board.board_points.filter(user=request.user).order_by('order')
    board_point_form = BoardPointForm(request.POST)
    if request.method == 'POST':
        if board_point_form.is_valid():
            last_point_order = board_points.aggregate(Max('order'))['order__max']
            next_order = (last_point_order or 0) + 1

            new_point = board_point_form.save(commit=False)
            new_point.board = board
            new_point.order = next_order
            new_point.user = request.user
            new_point.save()
            return redirect('board_draw', board_id=board_id)

    dots = board.dots.all()
    return render(request, 'Paths/board_draw.html', {
        'board': board,
        'ppts': board_points,
        'dots': dots,
        'cols': board.cols,
        'rows': board.rows,
        'point_form': board_point_form,
    })


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

django/PathEditor/Paths/templates/Paths/all_boards.html
{% extends 'Paths/base.html' %}

{% block title %}Twoje Plansze{% endblock %}

{% block content %}

{% if boards %}
    <span>Lista plansz wszystkich użytkowników:</span>
    <br>
    <ul> {% for board in boards %}
        <li>
            <a href="{% url 'board_draw' board.id %}">{{ board }} </a>
        </li>
    {% endfor %} </ul>

{% else %}
    <span>
        Nie ma aktualnie żadnych planszy.
    </span>
{% endif %}


{% endblock %}

django/PathEditor/Paths/templates/Paths/base.html
{% load static %}
{% now 'U' as now %}
<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My aplication{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'Paths/style.css' %}?v={{ now }}">
</head>

<body>
    <nav style="padding: 15px;">
        <span style="margin:10px;">
            <a href="{% url 'home' %}">Main site</a>
        </span>
        {% if user.is_authenticated %}
        <span style="margin:10px;">
            <a href="{% url 'select_background' %}">Choose a background</a>
        </span>
        <span style="margin:10px;">Witaj, {{ user.username }}!</span>
        <form action="{% url 'logout' %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit"
                style="background:none; border:none; color:white; cursor:pointer; padding: 0; margin: 0 10px; font-size: inherit;">Wyloguj</button>
        </form>
        {% else %}
        <span style="margin:10px;">
            <a href="{% url 'login' %}">Zaloguj</a>
        </span>
        {% endif %}
        <span style="margin:10px;">
            <a href="/admin/">Admin</a>
        </span>
    </nav>

    <div id="toast-container"></div>
    <script src="{% static 'Paths/sseService.js' %}?v={{ now }}">
    </script>
    <script>
        console.log("wtf");
        document.addEventListener('DOMContentLoaded', () => {
            console.log("Please start SSE");
            sseService.start();
        });
    </script>

    {% block content %}
    {% endblock %}

</body>

</html>

django/PathEditor/Paths/templates/Paths/bg_select.html
{% extends 'Paths/base.html' %}

{% block title %}Wybierz Tło{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}

        <hr>

        <h2>Dostępne tła:</h2>
        {% if backgrounds %}
            <div style="display: flex; flex-wrap: wrap; gap: 20px;">
                {% for background in backgrounds %}
                    <div style="border: 1px solid #eee; padding: 10px; text-align: center;">
                        <label for="background_{{ background.id }}">
                            <img src="{{ background.image.url }}" alt="{{ background.name }}" width="200" style="display: block; margin-bottom: 10px; cursor: pointer;">
                            <input type="radio" name="background_id" value="{{ background.id }}" id="background_{{ background.id }}"
                                {% if current_background and current_background.id == background.id %}checked{% endif %}>
                            {{ background.name }}
                        </label>
                    </div>
                {% endfor %}
            </div>

            <button type="submit" style="margin-top: 20px; padding: 10px 20px;">Zapisz wybór</button>
        {% else %}
            <p>Obecnie nie ma dostępnych żadnych teł. Administrator musi je dodać.</p>
        {% endif %}

    </form>
{% endblock %}

django/PathEditor/Paths/templates/Paths/board_detail.html
{% extends 'Paths/base.html' %}
{% load static %}

{% block content %}

<ul id="original-dots" style="display: none;">
    {% for dot in dots %}
    <li>
        <div>{{ dot.row }}</div>
        <div>{{ dot.col }}</div>
        <div>{{ dot.color }}</div>
    </li>
    {% endfor %}
</ul>

<script src="{% static 'Paths/board.js' %}?v={{ now }}">
</script>

<div style="display: flex; gap: 20px">
    <div id="board-container">
        <table id="board-table">
        </table>
    </div>

    <div>
        width of the board: <span id="cols">{{ cols }}</span>
        <br>
        height of the board: <span id="rows">{{ rows }}</span>

        <p>select color for the next points:</p>
        <div id="color-selector">
            <div class="color-line">
                <div class="color-block" style="background-color: blue;"> </div>
                <div class="color-text">blue</div>
            </div>
            <div class="color-line">
                <div class="color-block" style="background-color: red;"> </div>
                <div class="color-text">red</div>
            </div>
            <div class="color-line">
                <div class="color-block" style="background-color: green;"> </div>
                <div class="color-text">green</div>
            </div>
            <div class="color-line">
                <div class="color-block" style="background-color: yellow;"> </div>
                <div class="color-text">yellow</div>
            </div>
        </div>

        <div class="color-line">
            <div class="color-text">Selected color: </div>
            <div id="selected-color-name" class="color-text"> none </div>
            <div id="selected-color-block" class="color-block"></div>
        </div>

    </div>

</div>

<form method="POST">
    {% csrf_token %}
    <textarea style="display: none;" id="id_points" name="points"></textarea>
    <button id="submit-button" type="submit" onclick="serialize_points()">Zapisz planszę</button>
</form>

<script>
    document.addEventListener("DOMContentLoaded", () => {

        let selected_color_name = document.getElementById("selected-color-name");
        let selected_color_block = document.getElementById("selected-color-block");
        function setColorSwitcher(child) {
            const colorBlock = child.children[0];
            const color = window.getComputedStyle(colorBlock).backgroundColor;
            color_usage.set(color, 0);
            console.log(color);
            child.addEventListener("click", () => {
                console.log("Color: " + color);
                console.log("Current color: " + current_color);

                if (current_color == color) {
                    current_color = null;
                    selected_color_name.textContent = "none";
                    selected_color_block.style.backgroundColor = null;
                    return
                }

                current_color = color;
                console.log("Switched to: " + current_color);
                selected_color_name.textContent = child.children[1].textContent;
                selected_color_block.style.backgroundColor = color;
            })
        }

        const color_selector = document.getElementById("color-selector");
        if (!color_selector) {
            console.error("color selector not found");
        }
        for (const child of color_selector.children) {
            setColorSwitcher(child);
        }


        build_table();
        add_previous_points();


        function select_element(cell, row_number, col_number) {
            if (current_color == null) {
                remove_marker(cell, row_number, col_number);
            } else {
                add_marker(cell, row_number, col_number, current_color);
            }
            update_submit();
        }

        for (let i = 0; i < row_count; ++i) {
            for (let j = 0; j < col_count; ++j) {
                let element = table.children[i].children[j];
                element.addEventListener("click", () => select_element(element, i, j));
            }
        }

        
    })
</script>

{% endblock %}

django/PathEditor/Paths/templates/Paths/board_draw.html
{% extends 'Paths/base.html' %}
{% load static %}

{% block content %}

<ul id="original-dots" style="display: none;">
    {% for dot in dots %}
    <li>
        <div>{{ dot.row }}</div>
        <div>{{ dot.col }}</div>
        <div>{{ dot.color }}</div>
    </li>
    {% endfor %}
</ul>

<ul id="given-points" style="display: none;">
    {% for pp in ppts %}
    <li>
        <div>{{ pp.row }}</div>
        <div>{{ pp.col }}</div>
        <div>{{ pp.color }}</div>
    </li>
    {% endfor %}
</ul>

<script src="{% static 'Paths/board.js' %}?v={{ now }}"></script>

<span id="cols" style="display:none">{{ cols }}</span>
<span id="rows" style="display:none">{{ rows }}</span>

<div style="width: fit; height: fit;">
    <div id="board-container">
        <table id="board-table">
        </table>
    </div>
    <svg id="svg" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none;">
        <polyline id="polyline" points="" style="fill:none; stroke:red; stroke-width:3;" />
    </svg>
</div>


<hr style="margin-top: 30px;">
<h3>Dodaj nowy punkt na koniec</h3>
<form method="post">
    {% csrf_token %}
    {{ point_form.as_p }}
    <button type="submit">Dodaj Punkt</button>
</form>

<script>

    

    let rect;
    document.addEventListener("DOMContentLoaded", function () {
        build_table();
        add_previous_points();

        let polyline = document.getElementById("polyline");
        let points = document.getElementById("given-points");
        let parsedPoints = "";

        let el0 = table.children[0].children[0]
        rect = el0.getBoundingClientRect();

        let size = parseInt(rect.width)
        console.log(size);
        
        let offsetx = parseInt(rect.left);
        let offsety = parseInt(rect.top);
        for (let i = 0; i < points.children.length; ++i) {
            let data = points.children[i];
            let row = parseInt(data.children[0].textContent);
            let col = parseInt(data.children[1].textContent);

            let coordx = (col + 0.5) * size + offsetx;
            let coordy = (row + 0.5) * size + offsety;
            //console.log(col, row);
            console.log(coordx, coordy);
            parsedPoints += coordx + ", " + coordy + " ";

        }
        polyline.setAttribute("points", parsedPoints);


        const formRow = document.querySelector('input[name="row"]');
        if (!formRow) {
            console.error("formRow not found");
        }
        const formCol = document.querySelector('input[name="col"]');
        if (!formCol) {
            console.error("formCol not found");
        }
        const form = formCol.form;

        for (let i = 0; i < row_count; ++i) {
            let irow = table.children[i];
            for (let j = 0; j < col_count; ++j) {
                let ijel = irow.children[j];

                ijel.addEventListener("click", function () {
                    formRow.value = i.toString();
                    formCol.value = j.toString();
                    form.submit();
                })
            }
        }
    });
</script>

{% endblock %}

django/PathEditor/Paths/templates/Paths/board_form.html
{% extends 'Paths/base.html' %}

{% block title %}Utwórz nową planszę{% endblock %}

{% block content %}
<h2>Nowa Plansza</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Zapisz</button>
</form>
{% endblock %}}

django/PathEditor/Paths/templates/Paths/board_list.html
{% extends 'Paths/base.html' %}

{% block title %}Twoje Plansze{% endblock %}

{% block content %}

{% if boards %}
    <span>Lista twoich plansz:</span>
    <br>
    <ul> {% for board in boards %}
        <li>
            <a href="{% url 'board_detail' board.id %}">{{ board }} </a>
        </li>
    {% endfor %} </ul>

{% else %}
    <span>
        Nie masz aktualnie żadnych planszy
    </span>
{% endif %}


{% endblock %}

django/PathEditor/Paths/templates/Paths/edit_path.html
{% extends 'Paths/base.html' %}

{% block title %}Edytuj Trasę: {{ route.name }}{% endblock %}

{% block content %}
    <h1>Edytuj Trasę: {{ route.name }}</h1>
    <p><a href="{% url 'route_detail' route.id %}">&laquo; Anuluj i wróć do szczegółów trasy</a></p>

    {% if messages %}
        {% for message in messages %}
            <div class="messages {{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Zapisz Zmiany</button>
    </form>
{% endblock %}

django/PathEditor/Paths/templates/Paths/home.html
{% extends 'Paths/base.html' %}

{% block title %}Main site{% endblock %}

{% block content %} 
<span>Please log in to continue</span>
{% endblock %}

django/PathEditor/Paths/templates/Paths/main.html
{% extends 'Paths/base.html' %}

{% block title %} Strona głowna {% endblock %}


{% block content %} 

<a href="{% url 'path_list' %}"> Lista twoich ścieżek </a>
<br>
<a href="{% url 'board_list' %}"> Lista twoich plansz </a>
<br>
<a href="{% url 'allboard_list' %}"> Lista wszystkich plansz </a>

{% endblock %}

django/PathEditor/Paths/templates/Paths/path_detail.html
{% extends 'Paths/base.html' %}
{% load static %}

{% block title %}Szczegóły Trasy: {{ route.title }}{% endblock %}

{% block content %}
<h1>Trasa: {{ route.title }}</h1>
<p><a href="{% url 'path_list' %}">&laquo; Powrót do listy tras</a></p>
<p><strong>Tło:</strong> {{ background.title }}</p>

<h2>Wizualizacja Trasy</h2>
<div id="background-img-container" style="margin-bottom: 20px; border: 1px solid #ccc; position: relative; display: inline-block;">
  <img id="background-img" src="{{ background.image.url }}" alt="Tło trasy {{ route.title }}"
    style="max-width: 100%; display: block;">
  <script src="{% static 'Paths/pointOnBackground.js' %}?v={{ now }}"></script>

  {% if background.image.width and background.image.height %}
  <svg id="svg" width="100%" height="100%" viewBox="0 0 {{ background.image.width }} {{ background.image.height }}"
    style="position: absolute; top: 0; left: 0; pointer-events: none;">
    {% if points|length > 1 %}
    <polyline points="{% for point in points %}{{ point.x }},{{ point.y }} {% endfor %}"
      style="fill:none; stroke:red; stroke-width:3;" />
    {% endif %}
  </svg>
  {% else %}
  <p style="color: red;">Nie można wyświetlić wizualizacji - brak danych o wymiarach obrazka tła.</p>
  {% endif %}
</div>

<hr style="clear: both;">
<h2>Punkty trasy w kolejności</h2>

{% if points %}
<table id="point_table" border="1" style="width: 100%; border-collapse: collapse; margin-top: 15px;">
  <thead>
    <tr>
      <th>X</th>
      <th>Y</th>
      <th>Akcje</th>
    </tr>
  </thead>
  <tbody>
    {% for point in points %}
    <tr>
      <td>{{ point.x }}</td>
      <td>{{ point.y }}</td>
      <td>
        <form action="{% url 'point_delete' point.id %}" method="post" style="display: inline;">
          {% csrf_token %}
          <button type="submit" style="color: red; background: none; border: none; cursor: pointer;">[Usuń]</button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>Ta trasa nie ma jeszcze żadnych punktów.</p>
{% endif %}

<hr style="margin-top: 30px;">
<h3>Dodaj nowy punkt na koniec</h3>
<form method="post">
  {% csrf_token %}
  {{ point_form.as_p }}
  <button type="submit">Dodaj Punkt</button>
</form>

{% endblock %}

django/PathEditor/Paths/templates/Paths/path_form.html
{% extends 'Paths/base.html' %}

{% block title %}Utwórz nową trasę{% endblock %}

{% block content %}
<h2>Nowa Trasa</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Zapisz</button>
</form>
{% endblock %}